name: Build & Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build
      - run: pnpm zip

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: .output/cc98-live-better-*.zip
          generate_release_notes: true
